# Copyright (c) 2022 The xlandsat developers.
# Distributed under the terms of the MIT License.
# SPDX-License-Identifier: MIT
"""
Operations to enhance composites. Basically wrappers for skimage.exposure.
"""
import skimage.exposure


def equalize_histogram(composite, kernel_size=None, clip_limit=0.01):
    """
    Adaptive histogram equalization on each band of a composite

    Use this function to enhance the contrast of a composite when there are a
    few very dark or very light patches that dominate the color range. Use this
    instead of rescaling intensity (contrast stretching) to try to preserve
    some detail in the light/dark patches.

    This is a wrapper around :func:`skimage.exposure.equalize_adapthist`.

    .. tip::

        Results can be very bad if there are missing values in the scene. Use
        :func:`xlandsat.interpolate_missing` first if that is the case.

    If the composite has an alpha channel (transparency), it will be copied to
    the output intact.

    Parameters
    ----------
    composite : :class:`xarray.DataArray`
        A composite, as generated by :func:`xlandsat.composite`.
    kernel_size : int or None
        The size of region used in the algorithm. See
        :func:`skimage.exposure.equalize_adapthist` for details and defaults.
    clip_limit : float
        Clipping limit, normalized between 0 and 1 (higher values give more
        contrast).

    Returns
    -------
    equalized_composite : :class:`xarray.DataArray`
        The composite after equalization, scaled back to unsigned 8-bit integer
        range.
    """
    result = composite.copy(deep=True)
    for i in range(3):
        result.values[:, :, i] = skimage.exposure.rescale_intensity(
            skimage.exposure.equalize_adapthist(
                result.values[:, :, i],
                kernel_size=kernel_size,
                clip_limit=clip_limit,
            ),
            out_range="uint8",
        )
    return result
